
GET http://localhost:5000/api/post-detail/quy-trinh-phat-trien-game-tu-a-den-z

###
POST http://localhost:5000/api/send-mail
Content-Type: application/json
{"Fullname":"Hoàng Anh Văn","phoneNumber":"0.96946454","emailAddress":"admin@123"}
