
GET http://localhost:5000/api/get-posts

###
POST http://localhost:5000/api/send-mail
Content-Type: application/json
{"Fullname":"Hoàng Anh Văn","phoneNumber":"0.96946454","emailAddress":"admin@123"}
